import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ReportOverview } from '../types/report'

const money = (value: number) => `BDT ${value.toLocaleString('en-BD', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

const safeFileDate = (value: string) => value.replace(/[^0-9-]/g, '')

function downloadBlob(content: BlobPart, mimeType: string, fileName: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}

function csvCell(value: string | number) {
  const text = String(value ?? '')
  return `"${text.replace(/"/g, '""')}"`
}

export function exportReportCsv(report: ReportOverview) {
  const rows: Array<Array<string | number>> = [
    ['TechPOS Sales Report'],
    ['From', report.fromDate, 'To', report.toDate],
    [],
    ['Summary'],
    ['Metric', 'Value'],
    ['Total Sales', money(report.totalSales)],
    ['Orders', report.orders],
    ['Items Sold', report.itemsSold],
    ['Average Order Value', money(report.averageOrderValue)],
    ['Gross Profit', money(report.grossProfit)],
    ['Inventory Cost Value', money(report.inventoryCostValue)],
    ['Inventory Retail Value', money(report.inventoryRetailValue)],
    [],
    ['Sales Trend'],
    ['Date', 'Sales', 'Orders'],
    ...report.salesTrend.map((item) => [item.date, money(item.sales), item.orders]),
    [],
    ['Top Products'],
    ['Product', 'SKU', 'Quantity Sold', 'Revenue'],
    ...report.topProducts.map((item) => [item.productName, item.sku, item.quantitySold, money(item.revenue)]),
    [],
    ['Low Stock'],
    ['Product', 'SKU', 'Current Stock', 'Threshold'],
    ...report.lowStockProducts.map((item) => [item.productName, item.sku, item.stockQuantity, item.lowStockThreshold]),
  ]

  const csv = rows.map((row) => row.map(csvCell).join(',')).join('\r\n')
  downloadBlob(`\uFEFF${csv}`, 'text/csv;charset=utf-8', `techpos-sales-report-${safeFileDate(report.fromDate)}-to-${safeFileDate(report.toDate)}.csv`)
}

export function exportReportPdf(report: ReportOverview) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('TechPOS Sales Report', 14, 18)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(90)
  doc.text(`Period: ${report.fromDate} to ${report.toDate}`, 14, 25)
  doc.setTextColor(0)

  autoTable(doc, {
    startY: 32,
    head: [['Metric', 'Value']],
    body: [
      ['Total Sales', money(report.totalSales)],
      ['Orders', String(report.orders)],
      ['Items Sold', String(report.itemsSold)],
      ['Average Order Value', money(report.averageOrderValue)],
      ['Gross Profit', money(report.grossProfit)],
      ['Inventory Cost Value', money(report.inventoryCostValue)],
      ['Inventory Retail Value', money(report.inventoryRetailValue)],
    ],
    styles: { fontSize: 9 },
    headStyles: { fillColor: [30, 64, 175] },
  })

  autoTable(doc, {
    startY: (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ? (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8 : 85,
    head: [['Date', 'Sales', 'Orders']],
    body: report.salesTrend.map((item) => [item.date, money(item.sales), String(item.orders)]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [51, 65, 85] },
  })

  autoTable(doc, {
    startY: (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8,
    head: [['Top Product', 'SKU', 'Qty', 'Revenue']],
    body: report.topProducts.map((item) => [item.productName, item.sku, String(item.quantitySold), money(item.revenue)]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [51, 65, 85] },
  })

  autoTable(doc, {
    startY: (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8,
    head: [['Low Stock Product', 'SKU', 'Stock', 'Threshold']],
    body: report.lowStockProducts.map((item) => [item.productName, item.sku, String(item.stockQuantity), String(item.lowStockThreshold)]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [51, 65, 85] },
  })

  const pageCount = doc.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page)
    doc.setFontSize(8)
    doc.setTextColor(130)
    doc.text(`Generated by TechPOS · Page ${page} of ${pageCount}`, 14, 289)
  }

  doc.save(`techpos-sales-report-${safeFileDate(report.fromDate)}-to-${safeFileDate(report.toDate)}.pdf`)
}
